services:
  web:
    build: .
    ports:
      - "8080:80"  # WordPress accessible on port 8080
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=mydb
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    dns:
      - 8.8.8.8
      - 8.8.4.4

  wordpress:
    image: wordpress:latest
    ports:
      - "8081:80"  # WordPress container mapped to port 8081
    volumes:
      - ./www:/var/www/html  # Mount the WordPress directory
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: mydb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"  # phpMyAdmin accessible on port 8082
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data:
